Ai drug assistant
LangbaseInc/langbase-examples pull request #2
Opened 2024-07-13 00:13 UTC by AIENGINE

Pipe example: AI Drug Assistant

2024-07-15 14:35 UTC, msaaddev commented
@AIENGINE I assume its a duplicate of the current example with a few changes. Can you please list down the files you have changed in this PR so we can review it quickly? Thank you!

2024-07-15 21:21 UTC, AIENGINE commented
- updated chat interface text in opening.tsx, readme.md, and header.tsx

Please let me know if more details are required

2024-07-16 21:35 UTC, msaaddev commented on examples/ai-drug-assistant/components/opening.tsx
> +                <span>Use LangUI.dev's open source code compnents</span>
There is a typo in `components`

2024-07-16 21:36 UTC, msaaddev commented on examples/ai-drug-assistant/package.json
> +  "name": "langbase-chatbot-example",
Please update the project name here

2024-07-16 21:36 UTC, msaaddev commented on examples/ai-drug-assistant/app/layout.tsx
> +  description: 'Build an AI Chatbot with ⌘ Langbase using any LLM model.',
Please update name and description here

2024-07-16 21:41 UTC, msaaddev commented on examples/ai-drug-assistant/README.md
> +# Install the dependencies using the following command:
The env file and the shell script should be separate code block like

```env.local
# Replace `PIPE_API_KEY` with the copied API key.
NEXT_LB_PIPE_API_KEY="PIPE_API_KEY"
```

Now run the following commands in your terminal:

```sh
# Install the dependencies using the following command:
npm install

# Run the project using the following command:
npm run dev
```

2024-07-16 21:43 UTC, msaaddev commented on examples/ai-drug-assistant/README.md
> +- Muhammad-Ali Danish - Software Engineer, [Langbase][lb]
Better to only add your name here since you are the author even if you duplicated.

2024-07-23 11:58 UTC, ahmadbilaldev requested changes
Update the screenshot. Otherwise LGTM.

2024-07-23 21:19 UTC, ahmadbilaldev approved these changes

2024-07-23 21:19 UTC, merged